FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libgl1-mesa-dri \
        libglx-mesa0 \
        libx11-6 \
        libxext6 \
        libxrender1 \
        xauth \
        xvfb \
    && rm -rf /var/lib/apt/lists/*
